export const LANGUAGE_OPTIONS = [
  { label: "Javascript", value: "javascript" },
  { label: "Typescript", value: "typescript" },
  { label: "Css", value: "css" },
  { label: "Html", value: "html" },
  { label: "C", value: "c" },
  { label: "C#", value: "csharp" },
  { label: "C++", value: "cpp" },
  { label: "Dart", value: "dart" },
  { label: "Dockerfile", value: "dockerfile" },
  { label: "Go", value: "go" },
  { label: "Java", value: "java" },
  { label: "JSON", value: "json" },
  { label: "Kotlin", value: "kotlin" },
  { label: "Less", value: "less" },
  { label: "Markdown", value: "markdown" },
  { label: "Pascal", value: "pascal" },
  { label: "PHP", value: "php" },
  { label: "Plain Text", value: "plaintext" },
  { label: "Protobuf", value: "protobuf" },
  { label: "Python", value: "python" },
  { label: "Ruby", value: "ruby" },
  { label: "Rust", value: "rust" },
  { label: "Scala", value: "scala" },
  { label: "Scss", value: "scss" },
  { label: "Shell", value: "shell" },
  { label: "SQL", value: "sql" },
  { label: "Swift", value: "swift" },
  { label: "Visual Basic", value: "vb" },
  { label: "XML", value: "xml" },
  { label: "Yaml", value: "yaml" },
];

export const THEME_OPTIONS = [
  // Dark themes
  { label: "Abcdef", value: "abcdef" },
  { label: "Abyss", value: "abyss" },
  { label: "Android Studio", value: "androidstudio" },
  { label: "Andromeda", value: "andromeda" },
  { label: "Atom One", value: "atomone" },
  { label: "Aura", value: "aura" },
  { label: "Basic Dark", value: "basicDark" },
  { label: "Bespin", value: "bespin" },
  { label: "Console Dark", value: "consoleDark" },
  { label: "Copilot", value: "copilot" },
  { label: "Darcula", value: "darcula" },
  { label: "Dracula", value: "dracula" },
  { label: "Duotone Dark", value: "duotoneDark" },
  { label: "GitHub Dark", value: "githubDark" },
  { label: "Gruvbox Dark", value: "gruvboxDark" },
  { label: "Kimbie", value: "kimbie" },
  { label: "Material", value: "material" },
  { label: "Material Dark", value: "materialDark" },
  { label: "Monokai", value: "monokai" },
  { label: "Monokai Dimmed", value: "monokaiDimmed" },
  { label: "Nord", value: "nord" },
  { label: "Okaidia", value: "okaidia" },
  { label: "Red", value: "red" },
  { label: "Solarized Dark", value: "solarizedDark" },
  { label: "Sublime", value: "sublime" },
  { label: "Tokyo Night", value: "tokyoNight" },
  { label: "Tokyo Night Storm", value: "tokyoNightStorm" },
  { label: "Tomorrow Night Blue", value: "tomorrowNightBlue" },
  { label: "VS Code Dark", value: "vscodeDark" },
  { label: "White Dark", value: "whiteDark" },
  { label: "Xcode Dark", value: "xcodeDark" },

  // Light themes
  { label: "Basic Light", value: "basicLight" },
  { label: "BBEdit", value: "bbedit" },
  { label: "Console Light", value: "consoleLight" },
  { label: "Duotone Light", value: "duotoneLight" },
  { label: "Eclipse", value: "eclipse" },
  { label: "GitHub Light", value: "githubLight" },
  { label: "Gruvbox Light", value: "gruvboxLight" },
  { label: "Material Light", value: "materialLight" },
  { label: "Noctis Lilac", value: "noctisLilac" },
  { label: "Quietlight", value: "quietlight" },
  { label: "Solarized Light", value: "solarizedLight" },
  { label: "Tokyo Night Day", value: "tokyoNightDay" },
  { label: "VS Code Light", value: "vscodeLight" },
  { label: "White Light", value: "whiteLight" },
  { label: "Xcode Light", value: "xcodeLight" },
];
export const FONT_FAMILY_OPTIONS = [
  { label: "Jetbrains Mono", value: "jetbrains-mono" },
  { label: "Geist Mono", value: "geist-mono" },
  { label: "Agave", value: "agave" },
  { label: "Fira Code", value: "fira-code" },
  { label: "IBM Plex Mono", value: "ibm-plex-mono" },
  { label: "Source Code pro", value: "source-code-pro" },
  { label: "Space Mono", value: "space-mono" },
  { label: "Cascadia Code", value: "cascadia-code" },
];

export const FONT_WEIGHT_OPTIONS = [
  { label: "Regular", value: "regular" },
  { label: "Medium", value: "medium" },
  { label: "Bold", value: "bold" },
  { label: "Light", value: "light" },
];

export const FRAME_PADDING_OPTIONS = [
  { label: "16", value: "16" },
  { label: "32", value: "32" },
  { label: "64", value: "64" },
  { label: "128", value: "128" },
];

export const FRAME_RADIUS_OPTIONS = [
  { label: "0", value: "0" },
  { label: "8", value: "8" },
  { label: "16", value: "16" },
  { label: "24", value: "24" },
];

export const ASPECT_RATIO_OPTIONS = [
  { label: "Auto", value: "auto" },
  { label: "16:9", value: "16:9" },
  { label: "4:3", value: "4:3" },
  { label: "1:1", value: "1:1" },
];
